import { apiClient } from "./axios";

/**
 * ============================================================
 * Get My Tickets
 * ============================================================
 *
 * GET /api/v1/tickets/me
 *
 * Returns tickets belonging to the
 * currently authenticated user.
 */

export const getMyTickets = async () => {
  const { data } = await apiClient.get(
    "/tickets/me",
  );

  return (
    data?.data?.tickets ||
    []
  );
};

/**
 * ============================================================
 * Get Public Tickets (Guest)
 * ============================================================
 *
 * GET /api/v1/tickets/public/:registrationId
 */

export const getPublicTickets = async (registrationId, guestToken) => {
  if (!registrationId) {
    throw new Error("Registration ID is required.");
  }
  if (!guestToken) {
    throw new Error("Guest token is required.");
  }

  const { data } = await apiClient.get(
    `/tickets/public/${registrationId}`,
    {
      headers: {
        "X-Guest-Token": guestToken,
      },
    }
  );

  return (
    data?.data?.tickets ||
    []
  );
};

/**
 * ============================================================
 * Get Ticket QR
 * ============================================================
 *
 * GET /api/v1/tickets/:id/qr
 *
 * Returns:
 *
 * {
 *   ticketNumber,
 *   qrCode
 * }
 */

export const getTicketQR =
  async (ticketId) => {
    if (!ticketId) {
      throw new Error(
        "Ticket ID is required.",
      );
    }

    const { data } =
      await apiClient.get(
        `/tickets/${ticketId}/qr`,
      );

    return (
      data?.data || {}
    );
  };

/**
 * ============================================================
 * Verify Ticket QR
 * ============================================================
 *
 * POST /api/v1/tickets/verify
 *
 * The QR scanner sends the complete QR payload
 * generated by Scintillace.
 *
 * Request body:
 *
 * {
 *   qrPayload: "{\"type\":\"SCINTILLACE_TICKET\",...}"
 * }
 *
 * The backend:
 *
 * 1. Parses the QR payload.
 * 2. Validates the QR type.
 * 3. Finds the ticket.
 * 4. Verifies the secure QR token.
 * 5. Checks ticket status.
 *
 * Verification DOES NOT perform check-in.
 *
 * Returns:
 *
 * {
 *   ticket,
 *   valid
 * }
 */

export const verifyTicketQR =
  async (qrPayload) => {
    if (
      typeof qrPayload !==
        "string" ||
      !qrPayload.trim()
    ) {
      throw new Error(
        "QR payload is required.",
      );
    }

    const { data } =
      await apiClient.post(
        "/tickets/verify",
        {
          qrPayload:
            qrPayload.trim(),
        },
      );

    return (
      data?.data || {}
    );
  };

/**
 * ============================================================
 * Check In Ticket
 * ============================================================
 *
 * PATCH /api/v1/tickets/:id/check-in
 *
 * Allowed roles:
 *
 * - SUPER_ADMIN
 * - FACULTY
 * - VOLUNTEER
 *
 * This should only be called after
 * successful QR verification.
 */

export const checkInTicket =
  async (ticketId) => {
    if (!ticketId) {
      throw new Error(
        "Ticket ID is required.",
      );
    }

    const { data } =
      await apiClient.patch(
        `/tickets/${ticketId}/check-in`,
      );

    return (
      data?.data?.ticket ||
      null
    );
  };

/**
 * ============================================================
 * Tickets API Export
 * ============================================================
 */

const ticketsApi =
  Object.freeze({
    getMyTickets,
    getPublicTickets,
    getTicketQR,
    verifyTicketQR,
    checkInTicket,
  });

export default ticketsApi;
